name: 'Dispatch'
description: 'Dispatch an onchange event to run webhook'
author: 'Gennadiy Khatuntsev <e.steelcat@gmail.com>'

inputs:
  access_token:
    description: 'Token for the repo'
    required: true

  event_target:
    description: 'Target repository is configured to build on the webhook'
    required: true

  event_type:
    description: 'Event type to dispatch'
    required: true

  payload_sender:
    description: 'App name'
    required: true

  payload_ref:
    description: 'Ref to checkout (SHA, branch, tag)'
    required: true

runs:
  using: 'docker'
  image: './Dockerfile'
